Changes snaptec repo (#856)
* refactor smart home device configuration MQTT-listener for readability, better log output and less code

* speed up checking for and installing python packages

* at_reboot.sh: install lxml via apt-get instead via pip3

* Use unit of FEMS response to adjust value

* Indenting with tabs again

* Fix copy error

* soc_evcc: add pin for fiat

Fiat requires an app pin for SoC access, so add optional field to
enter that pin and only use it if car type is fiat.

* Smartfox (#2551)

* with old version

* add smartfox

* smarthome fix (#2634)

Verzeichnispfad von Lambda an neuen Verzeichnispfad Lambda_ angepasst.
Ratiotherm alter PR angepasst (Dynregel)
Lambda und Ratiotherm unötiger print entfernt

* fix pin lock in "symbolfluss" display theme

* format fixes

* separate remote support from other processes

* backport changes from 2.0

* restore old remote support handling for parallel testing

* fix python 3.5 incompatibility

* remove lxml from pip package list

* Update modules/speicher_fems/fems.py

Co-authored-by: benderl <benderl@users.noreply.github.com>

* Update modules/wr_fems/fems.py

Co-authored-by: benderl <benderl@users.noreply.github.com>

* Apply suggestions from code review

Co-authored-by: benderl <benderl@users.noreply.github.com>

* correct autarchy calculation

* soc_vwid: sync libvwid.py from source repository

* Fix wrong case-senstive comparisions

* Code cleanup according

https://github.com/snaptec/openWB/pull/2629#pullrequestreview-1332186550

* Fix static code analysis complains

* add powerfox (#2554)

* add powerfox

* fix deviceconfig

* Include revie comments

Many thanks to @yankee42 !

* fix code analysis complains

* Fix display theme icons

* Add icons to powermeter

* Change subtitle in yieldmeter

* Fixl line ending

* Add space to title of chargepoint widget

* modify widget titles

* Update style.css

One "Solid" bei mir nur HexZahlen (oder Ersatzzeichen FF)

* fix battery initial setting

* fix font selection error

* Modbus tty acm0 (#2642)

* add ttyACM0

* fix parsing in setChargingCurrentWifi

* fix flake8 and shellcheck warnings

* fix

* fix duo

* python 2 -> 3 calls

* delete autoevse.py

---------

Co-authored-by: Lutz Bender <lutz@lutz-bender.de>
Co-authored-by: LKuemmel <lena.kuemmel@openwb.de>

* Fix isss (#2601)

* fix isss: Ändern des NurLP-Modus

* fix

* don't overwrite own values

* fix local daemon

* reduce actor cooldown to 60s

* Fix icon and font problems

* Increase icon size

* code cleanup

* fix smart home topic match

* format mqttsub.py

* remove pyt from smart home devices

* some python naming and formatting

* remove references to outdated smart home config file handler

* set execute bit of installPythonPackages.py

* add missed reread trigger for smarthome handler

* remove fixed orientation in manifest.json

* only start smarthome handler if not in isss mode

* check for evsecons1 to set isss duo mode

* start rse and push buttons handler only if not in isss mode

* separate isss mode selection and network setup

* formatting

* remove virtual IP handling in atreboot.sh

* format atreboot.sh

* fix phase detection edge cases

* fix smart home device manual control topic

* correct/add some shebangs

* fix modbus unit id

* Smarthome...

Shelly (gen = 1) mit userid + pw möglich
Fehler reset Manual mode um 23:59 gelöst
Vorbereitung Openwb 2.0:
maxbatteryPower aus MQTT
smartcon logging in smarthome.log integriert
in alle aufrufe (z.b. smartshelly) log aufrufe auf
import logging
log = logging.getLogger(__name__)
umgestellt
Manuelle Leistung für Elwa eingefügt (nur gui)

* flake8

* modify helptext "EVU Glättung"

* always store battery soc (2.0 backport)

* Revert "do not stop charging on additional charge points"

* prevent display gestures

* smarthomemq....

https://openwb.de/forum/viewtopic.php?p=82813#p82813
UnboundLocalError: local variable 'keyword' referenced before assignment
    elif (("/" in keyword) or (int(devicenumb) < 1) or
gelöst

* smarthomemq....

mqtt parameter  lesen stark vereinfach und neu strukturiert.
Getestet unter buster

* add note to huawei inverter configuration

* fix logging error with unicode characters

* restructure shelly inverter module

* Fix incorrect PV percentage

* Wake up Zoe

Es gibt immer noch Zoes, die fürs laden speziell geweckt werden müssen.
Flake8 Anpassungen gemacht und neuste Keys eingeführt

* file handler....

sorry hätte ich auch grad machen können...

* detect wrong house power in daily graph

* fix mercedes soc security bug

* cleanup main.sh

* update python files

* bump version 1.9.297

Beta 1.9.297

* bump version 1.9.298

* fix switch between parent and NurLP

* rewrite modbus tester

* review

* fix merge

---------

Co-authored-by: Yannik Hampe <yzeugs@cipher-code.de>
Co-authored-by: rleidner <rl111@gmx.de>
Co-authored-by: Kurt <dj3mu@darc.de>
Co-authored-by: ts78 <ts78@ist-einmalig.de>
Co-authored-by: okaegi <72255431+okaegi@users.noreply.github.com>
Co-authored-by: Lutz Bender <lutz@lutz-bender.de>
Co-authored-by: benderl <benderl@users.noreply.github.com>
Co-authored-by: dj3mu <41773089+dj3mu@users.noreply.github.com>
Co-authored-by: cshagen@hagens.ch <cshagen@hagens.ch>
Co-authored-by: Penny <89247538+hhoefling@users.noreply.github.com>
Co-authored-by: okaegi <okaegi@pinball4you.ch>