Fix Solis (#1990)
* Solis: fix modbus address for SOC

The Solis support was created based on Fox ESS. It looks like the
creator missed to adjust the modbus address for SOC, it's 33139 based
on a register map I got from solis support.

Total discharge energy is also in kWh, not 1/10kWh units.

* Solis: read all registers as input registers

Every modbus query fails, as all registers need to be read as input
registers (code 0x04), instead of holding register.

* Solis: Fix for unreachable local variables

right now I get the following error:
UnboundLocalError: local variable 'power' referenced before assignment

Fix it by moving some code around.

* Review

---------

Co-authored-by: LKuemmel <76958050+LKuemmel@users.noreply.github.com>